on:
  push:
    branches: [ main ]
  pull_request: { }

permissions:
  contents: read

jobs:
  required-meta:
    permissions:
      contents: read
      pull-requests: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v2

  check:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-check.yml@v4
    with:
      build-tool: uv
      python-version: "3.13"

  bump:
    uses: BlindfoldedSurgery/actions-releases/.github/workflows/commitizen-bump.yml@v4
    permissions:
      contents: write
      pull-requests: write
    with:
      build-tool: uv
      publish-major-tag: true
      python-version: "3.13"
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
