on:
  workflow_call:
    inputs:
      build-tool-version:
        type: string
        required: false
      cache-enabled:
        required: false
        type: boolean
        default: true
      cache-key-suffix:
        required: false
        type: string
      check-lockfile-exists:
        required: false
        type: boolean
        default: true
      python-version:
        required: true
        type: string
      type-checker:
        type: string
        required: false
        default: mypy
      debian-version:
        required: false
        type: string
        default: trixie
      context-path:
        required: false
        type: string
        default: src/

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    container: python:${{ inputs.python-version }}-slim-${{ inputs.debian-version }}
    env:
      # renovate: datasource=pypi depName=uv versioning=semver-coerced
      UV_VERSION: "0.11.7"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          cache-suffix: ${{ inputs.cache-key-suffix }}
          enable-cache: ${{ inputs.cache-enabled }}
          version: ${{ inputs.build-tool-version || env.UV_VERSION }}
      - run: uv sync --all-extras
      - name: Print deprecation warning
        if: inputs.type-checker != 'mypy'
        env:
          WARNING_TEXT: |
            ## Deprecation warning
            
            The type-checker parameter is deprecated. Use mypy or nothing.
        run: |
          printenv WARNING_TEXT >> "$GITHUB_STEP_SUMMARY"
      - name: Check coding standards
        run: |
          uv run ruff format --check ${{ inputs.context-path }}
          uv run ruff check ${{ inputs.context-path }}
          uv run ${{ inputs.type-checker }} ${{ inputs.context-path }}
