on:
  workflow_call:
    inputs:
      build-tool-version:
        type: string
        required: false
      cache-enabled:
        required: false
        type: boolean
        default: true
      cache-key-suffix:
        required: false
        type: string
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: trixie
      pypi-username:
        required: true
        type: string
    secrets:
      pypi-password:
        required: true

permissions:
  contents: read

jobs:
  publish-package:
    runs-on: ubuntu-24.04
    container: python:${{ inputs.python-version }}-slim-${{ inputs.debian-version }}
    env:
      # renovate: datasource=pypi depName=uv versioning=semver-coerced
      UV_VERSION: "0.11.3"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          cache-suffix: ${{ inputs.cache-key-suffix }}
          enable-cache: ${{ inputs.cache-enabled }}
          version: ${{ inputs.build-tool-version || env.UV_VERSION }}
      - name: Sync dependencies
        run: uv sync --all-extras
      - name: Build project
        run: uv build
      - name: Upload to pypi registry
        env:
          UV_PUBLISH_USERNAME: ${{ inputs.pypi-username }}
          UV_PUBLISH_PASSWORD: ${{ secrets.pypi-password }}
        run: |
          uv publish
