on:
  workflow_call:
    inputs:
      build-tool-version:
        type: string
        required: false
      cache-enabled:
        required: false
        type: boolean
        default: true
      cache-key-suffix:
        required: false
        type: string
      python-version:
        required: true
        type: string
      debian-version:
        required: false
        type: string
        default: trixie
      submit-coverage:
        required: false
        type: boolean
        default: false
      tests-location:
        required: false
        type: string
      tests-selector:
        required: false
        type: string
    secrets:
      ENVIRONMENT_VARIABLES:
        required: false
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-24.04
    container: python:${{ inputs.python-version }}-slim-${{ inputs.debian-version }}
    env:
      # renovate: datasource=pypi depName=uv versioning=semver-coerced
      UV_VERSION: "0.11.3"
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          cache-suffix: ${{ inputs.cache-key-suffix }}
          enable-cache: ${{ inputs.cache-enabled }}
          version: ${{ inputs.build-tool-version || env.UV_VERSION }}
      - run: uv sync --all-extras
      - name: Export secrets as environment
        env:
          INPUT_VARS: ${{ secrets.ENVIRONMENT_VARIABLES }}
        shell: bash
        run: |
          if [ -z "$INPUT_VARS" ]
          then
            echo "No env vars given."
            exit 0
          fi
          
          while IFS= read -r line
          do
            if [ -n "$line" ]
            then
              echo "::add-mask::$line"
              value=$(echo "$line" | cut -d"=" -f2-)
              echo "::add-mask::$value"
          
              echo "$line" >> "$GITHUB_ENV"
            fi
          done <<< "$INPUT_VARS"
      - name: Run tests
        run: uv run pytest ${{ inputs.tests-selector && format('-m "{0}"', inputs.tests-selector) || '' }} ${{ inputs.submit-coverage && '--cov --junitxml=junit.xml' || '' }} ${{ inputs.tests-location }}
      - name: Convert Python coverage file format to XML
        if: inputs.submit-coverage
        run: uv run coverage xml
      - name: Store coverage artifact
        if: inputs.submit-coverage
        uses: actions/upload-artifact@v7
        with:
          name: test-coverage
          path: |
            ./coverage.xml
            ./junit.xml
          overwrite: true

  upload-coverage-report:
    runs-on: ubuntu-24.04
    needs: [ test ]
    if: inputs.submit-coverage
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: test-coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          fail_ci_if_error: true
          files: ./coverage.xml
          report_type: coverage
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          disable_search: true
          fail_ci_if_error: true
          files: ./junit.xml
          report_type: test_results
